import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <aside>
          <h2>Task Management App</h2>
          <Link className="aside-item" href={"/"}>
            Home
          </Link>
          <Link className="aside-item" href={"/create-task"}>
            Create Task
          </Link>
          <Link className="aside-item" href={"/frontend"}>
            Frontend
          </Link>
          <Link className="aside-item" href={"/backend"}>
            Backend
          </Link>
          <Link className="aside-item" href={"/mobile"}>
            Mobile
          </Link>
        </aside>
        {children}
      </body>
    </html>
  );
}
